- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore:
    ~/.aria2/aria2.conf:
    ~/.axelrc:
    ~/.bash:
    ~/.bashrc:
    ~/.config/nvim/init.vim: vimrc_shared
    ~/.dotfiles: ''
    ~/.emacs.d:
    ~/.emacs:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.gnupg/gpg.conf:
    ~/.hgrc:
    ~/.inputrc:
    ~/.ipython/profile_default/ipython_kernel_config.py:
    ~/.rtorrent.rc:
    ~/.screenrc:
    ~/.shell:
    ~/.tmux.conf:
    ~/.vimrc: vimrc_shared
    ~/.zsh:
    ~/.zshrc:

- shell:
  - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads
  - curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  - curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  - vim +PlugInstall +qall
  - nvim +PlugInstall +qall
  - git update-submodules # after linking ~/.gitconfig
